name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4.2.0

      - name: Build base stage
        uses: docker/build-push-action@v7.3.0
        with:
          context: .
          file: docker/Dockerfile
          target: base
          load: true
          tags: elixir-docker-template:base

      - name: Build dev stage
        uses: docker/build-push-action@v7.3.0
        with:
          context: .
          file: docker/Dockerfile
          target: dev
          load: true
          tags: elixir-docker-template:dev

      - name: Build prod stage
        uses: docker/build-push-action@v7.3.0
        with:
          context: .
          file: docker/Dockerfile
          target: prod
          load: true
          tags: elixir-docker-template:prod

      - name: Validate compose
        run: docker compose config --quiet

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: docker/Dockerfile
          ignore: DL3008
